project:
  type: book

book:
  # <img src='img/logo_fjp.png' alt='Logo' style='vertical-align: middle; width:180px'>   
  title: "<img src='img/logo_fjp.png' alt='Logo' style='fig-align=center; width:100px'> Exploração do Lítio no Vale do Jequitinhonha"
  subtitle: "Características Demográficas e Sociais dos Municípios Potenciais"
  date: "05/31/2024"
  chapters:
    - index.qmd
    - fichatecnica.qmd
    - introducao.qmd
    - populacao.qmd
    - migracao.qmd
    - cadunico.qmd
    - migracaoaracuai.qmd
    - economia.qmd
    - social.qmd
    - equipamentos.qmd
    # - acoes.qmd
    - references.qmd
  sidebar:
    pinned: true
    
  search: 
    location: sidebar
    type: textbox
 
bibliography: 
    - references.bib

format:
  html:
    theme: Simplex
    mainfont: Arial
    base: /vale_litio/
  pdf:
    documentclass: scrreprt
lang: pt
editor: visual
