# Ficha Técnica {.unnumbered}

<br> <br>

**GOVERNADOR DO ESTADO DE MINAS GERAIS**

Romeu Zema Neto

**SECRETÁRIA DE ESTADO DE PLANEJAMENTO E GESTÃO**

Luísa Cardoso Barreto

<br>

**FUNDAÇÃO JOÃO PINHEIRO (FJP)**

Presidente

Luciana Lopes Nominato Braga

Vice-Presidente

Mônica Moreira Esteves Bernardi

<br>

**ASSESSORIA TÉCNICA DA PRESIDÊNCIA**

Mauro César da Silveira


**DIRETORIA DE ESTATÍSTICA E INFORMAÇÕES**

Claudio Djissey Shikida (Diretor)

Tomaz Duarte Moreira (Coordenador-Geral)

**Coordenação de Indicadores Sociais**

Caio Gonçalves

<br>


### Organizadores e autores
**Organizadores**

Caio Gonçalves

Vitor Marinho

**Autores**

-   Cap. 1: População e estrutura etária com o Censo Demográfico de 2022 - Caio Gonçalves e Vitor Marinho

-   Cap. 2: Movimentos migratórios com o Censo Demográfico até 2010 - Olinto Nogueira

-   Cap. 3: Utilizando o CadÚnico para os estudos de migração no período recente - Helena Soares

-   Cap. 4: Os fluxos migratórios de Aracuaí com o Censo Demográfico de 2010 - Cláudio Costa e Helena Soares

-   Cap. 5: Produção, exportações e o emprego - Vitor Marinho, Caio Gonçalves e Cláudio Shikida

-   Cap. 6: Aspectos sociais à luz do Índice Mineiro de Responsabilidade Social - Caio Gonçalves e Vitor Marinho

-   Cap. 7: Equipamentos de saúde e educação - Caio Gonçalves, Vitor Marinho e Cláudio Shikida

<!-- -   Cap. 8: Ações prioritárias de desenvolvimento - Caio Gonçalves e Cláudio Shikida -->

Os textos produzidos contaram com revisões e comentários de Renato Vale, Cláudio Costa e Cláudio Shikida.

<!-- **Capa** -->

<!-- \[\] -->

<!-- **Revisão** -->

<!-- \[\] -->

<!-- **Normalização** -->

<!-- \[\] -->

<!-- ### Detalhes do livro -->

<!-- -   **Tipo:** eBook -->

<!-- <!-- -   **ISBN:** \[solicitar\] --> 

<!-- -   **Ano da Edição:** 2024 -->

### Sugestão de citação

Gonçalves, Caio; Marinho, Vitor (org.). **Exploração do Lítio no Vale do Jequitinhonha: Características Demográficas e Sociais dos Municípios Potenciais**. Belo Horizonte: Fundação João Pinheiro, Diretoria de Estatística e Informações, 2024.
