# Prefácio {.unnumbered}

O propósito deste documento é fornecer informações relacionadas às características demográficas e socioeconômicas dos municípios que possuem potencial de exploração do lítio no Vale do Jequitinhonha. De forma simples e direta, este livro digital aborda uma gama de temas essenciais, incluindo dados demográficos, produção, emprego, vulnerabilidade, educação, saúde e saneamento básico. 
<!-- Além disso, destaca elementos identificados nos planos de desenvolvimento elaborados para a região em estudo. -->

Para garantir a qualidade das informações, utilizou-se os dados sistematizados na Plataforma do Índice Mineiro de Responsabilidade Social [IMRS](https://imrs.fjp.mg.gov.br/) da Fundação João Pinheiro, onde também é possível acessar perfis individuais de cada município [aqui](https://imrs.fjp.mg.gov.br/Perfil). As fontes de dados provêm de diversas origens, incluindo os dados mais recentes do Censo Demográfico de 2022 realizado pelo Instituto Brasileiro de Geografia e Estatística (IBGE).

**Perguntas orientadoras**:

Este prefácio também serve como um guia para as principais questões que o documento busca responder:

1.  [Quantas pessoas residem nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha? Qual foi a evolução populacional nos últimos 12 anos?](populacao.qmd#sec-quantas-pessoas-residem-nos-municípios-com-potencial-para-exploração-do-lítio-no-vale-do-jequitinhonha-qual-foi-a-evolução-populacional-nos-últimos-12-anos)

2.  [Qual é a estrutura etária atual dos municípios com potencial para exploração do lítio no Vale do Jequitinhonha? A população é predominantemente jovem ou envelhecida?](populacao.qmd#sec-estrutura-etaria)

3.  [Quais os movimentos migratórios observados nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha? É possível inferir sobre a última década sem os dados do Censo Demográfico de 2022?](migracao.qmd#sec-mig-censo)

4.  [O que os dados do CadÚnico podem revelar sobre características sociais da população em idade ativa presente no cadastro?](cadunico.qmd#sec-cad-unico)

5.  [O que é possível captar de migração com os dados do CadÚnico?](cadunico.qmd#sec-o-que-é-possível-captar-de-migração-com-os-dados-do-cadúnico)

6.  [Qual a estrutura etária e os fluxos migratórios observados especificamente em Araçuaí?](migracaoaracuai.qmd#sec-fluxo-aracuai)

7.  [Em termos da importância econômica das atividades presentes nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha, o que os dados dos PIB revelam?](economia.qmd#sec-qt1-economia)

8.  [Qual o quadro atual das exportações dos municípios com potencial para exploração do lítio no Vale do Jequitinhonha?](economia.qmd#sec-exportacao)

9.  [Qual a importância da indústria extrativa na geração de empregos formais nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha?](economia.qmd#sec-emprego-formal)

10. [Como está a situação social nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha de maneira geral?](social.qmd#sec-social-geral)

11. [O que revelam os principais indicadores da área da educação, saúde, assistência social, segurança pública e saneamento básico?](social.qmd#sec-indicador-educ)

12. [Qual a situação desses municípios em termos de equipamentos de saúde e educação? ](equipamentos.qmd#sec-qual-a-situação-desses-municípios-em-termos-de-equipamentos-de-saúde-e-educação)

<!-- 13. [O que dizem os planos de desenvolvimento realizados para a região sobre o lítio e as questões sociais?](acoes.qmd#sec-acoe-desv) -->
